branches:
  only:
    - "master"

language: go

go:
  - 1.10.x
  - master

env:
  - DEP_VERSION="0.5.0"

git:
  depth: 1  

notifications:
  email: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
